### ISSUE TITLE
Can't deploy with Truffle

### ISSUE THREAD

**Issue by Kevin-Mok** [application-research/fevm-nft-estuary#1]
I added my private key to `truffle-config.js` and ran:
```
npm install
truffle compile
truffle build
truffle deploy --network testnet
```
Everything went fine until the last step where I get:
```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Starting migrations...
======================
> Network name:    'testnet'
> Network id:      18
> Block gas limit: 10000000000 (0x2540be400)

1_initial_migration.js
======================

   Deploying 'Estuary721'
   ----------------------

Error:  *** Deployment Failed ***

"Estuary721" -- legacy transaction is not supported.

    at /usr/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Migration._deploy (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:75:1)
    at Migration._load (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:61:1)
    at Migration.run (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:218:1)
    at Object.runMigrations (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:258:1)
    at Object.run (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:167:1)
Truffle v5.4.1 (core: 5.4.1)
Node v18.7.0
```
How do you deploy using a EIP-1559 transaction?

**Comment by alvin-reyes** [comment]
It's working on my end (just tested it now again). 

I'm using Truffle v5.5.14 (core: 5.5.14) and Node v16.8.0

```
truffle deploy --network testnet
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.


Starting migrations...
======================
> Network name:    'testnet'
> Network id:      18
> Block gas limit: 10000000000 (0x2540be400)


1_initial_migration.js
======================

   Deploying 'Estuary721'
   ----------------------
   > transaction hash:    0x59f19d82ad5491b9ca453623d48abe0d2041a62c5bd3e4c1ff9f3c360233e31c
   > Blocks: 4            Seconds: 69
   > contract address:    0xBE0F1acc391e83e5c0E8889e7F4E02898716c4C1
   > block number:        27107
   > block timestamp:     1671320428
   > account:             0x82C0b66C79dbF90E1cA0A6571C07b2a7cc78219F
   > balance:             4992.388164600568193235
   > gas used:            213826047 (0xcbeb9ff)
   > gas price:           0 gwei
   > value sent:          0 ETH
   > total cost:          0 ETH

   Pausing for 10 confirmations...

   --------------------------------
   > confirmation number: 1 (block: 27109)
   > confirmation number: 2 (block: 27110)
   > confirmation number: 3 (block: 27111)
   > confirmation number: 4 (block: 27112)
   > confirmation number: 5 (block: 27113)
   > confirmation number: 6 (block: 27114)
   > confirmation number: 7 (block: 27115)
   > confirmation number: 8 (block: 27116)
   > confirmation number: 9 (block: 27117)
   > confirmation number: 10 (block: 27118)
   > Saving artifacts
   -------------------------------------
   > Total cost:                   0 ETH

Summary
=======
> Total deployments:   1
> Final cost:          0 ETH

```
[https://explorer.glif.io/tx/0x59f19d82ad5491b9ca453623d48abe0d2041a62c5bd3e4c1ff9f3c360233e31c/?network=wallaby](https://explorer.glif.io/tx/0x59f19d82ad5491b9ca453623d48abe0d2041a62c5bd3e4c1ff9f3c360233e31c/?network=wallaby)

**Comment by Kevin-Mok** [comment]
Turns out my package manager had Truffle version 5.4.1-1. I upgraded to 5.7.0, and it works now. Thanks for letting me know about the versions.
